### ISSUE TITLE
redis有无配置开关

### ISSUE THREAD

**Issue by chunjies** [kaixinzyw/fast-dao#1]
redis不是必要使用，有无配置开关

**Comment by kaixinzyw** [comment]
默认不开启redis
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"大虫"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月30日(星期六) 晚上7:57
 收件人:&nbsp;"kaixinzyw/fast-dao"<fast-dao@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[kaixinzyw/fast-dao] redis有无配置开关 (#1)

 

 
redis不是必要使用，有无配置开关
