### ISSUE TITLE
jdbc和数据源中间件有无适配

### ISSUE THREAD

**Issue by chunjies** [kaixinzyw/fast-dao#2]
1.HikariCP
2.Druid
3.DBCP 
4.C3P0
5.Tomcat Jdbc Pool
6.BoneCP
7.jndi

**Comment by kaixinzyw** [comment]
连接池任意选用,文档中多多数据源切换的例子就是使用阿里的连接池
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"大虫"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月30日(星期六) 晚上7:59
 收件人:&nbsp;"kaixinzyw/fast-dao"<fast-dao@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[kaixinzyw/fast-dao] jdbc和数据源中间件有无适配 (#2)

 

 
1.HikariCP
2.Druid
3.DBCP
4.C3P0
5.Tomcat Jdbc Pool
6.BoneCP
7.jndi
