### ISSUE TITLE
在指定文件夹中生成代码

### ISSUE THREAD

**Issue by chunjies** [kaixinzyw/fast-dao#3]
在指定文件夹中生成代码

**Comment by kaixinzyw** [comment]
设定的是标准maven结构项目代码生成,你可以生成后把代码拷贝过去
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"大虫"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月30日(星期六) 晚上11:23
 收件人:&nbsp;"kaixinzyw/fast-dao"<fast-dao@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[kaixinzyw/fast-dao] 在指定文件夹中生成代码 (#3)

 

 
在指定文件夹中生成代码
