### ISSUE TITLE
表前缀生成代码去不掉

### ISSUE THREAD

**Issue by chunjies** [kaixinzyw/fast-dao#4]
表 BS_SYS  生成代码需要去掉BS_  代码生成的是BsSys 并没去掉BS  去掉应该忽略大小写

**Comment by kaixinzyw** [comment]
使用FileCreateConfig.setPrefix 进行前缀配置
//例
FileCreateConfig config = new FileCreateConfig();
config.setPrefix(true,false,null);

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"大虫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月30日(星期六) 晚上11:34
收件人:&nbsp;"kaixinzyw/fast-dao"<fast-dao@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[kaixinzyw/fast-dao] 表前缀生成代码去不掉 (#4)




表 BS_SYS  生成代码需要去掉BS_  代码生成的是BsSys 并没去掉BS  去掉应该忽略大小写

**Comment by kaixinzyw** [comment]
同学,请阅读使用文档,你问的问题文档中都有使用说明的

**Comment by chunjies** [comment]
你最后一个参数无用？
